# railway.toml

[project]
name = "meu_projeto_n8n"

[plugins]

[plugins.n8n]
source = "Docker"
service = "n8n"
image = "n8nio/n8n:latest"
variables = [
  { name = "DB_TYPE", value = "postgresdb" },
  { name = "DB_POSTGRESDB_HOST", value = "postgres" },
  { name = "DB_POSTGRESDB_USER", value = "root" },
  { name = "DB_POSTGRESDB_PASSWORD", value = "password" },
  { name = "EXECUTIONS_MODE", value = "queue" },
  { name = "QUEUE_BULL_REDIS_HOST", value = "redis" },
  { name = "QUEUE_HEALTH_CHECK_ACTIVE", value = "true" },
  { name = "N8N_DIAGNOSTICS_ENABLED", value = "false" },
  { name = "N8N_PERSONALIZATION_ENABLED", value = "false" },
  { name = "N8N_ENCRYPTION_KEY", value = "F+n8T0pctpwp5gLqwjUGmsRZn2yrLNGz" },
  { name = "N8N_USER_MANAGEMENT_JWT_SECRET", value = "<seu_jwt_secret>" }
]
# Volumes do Railway configurados aqui
[plugins.n8n.volumes]
n8n_storage = "/home/node/.n8n"
backup = "/backup"
shared = "/data/shared"

[plugins.redis]
source = "Docker"
service = "redis"
image = "redis:6-alpine"
variables = []

[plugins.postgres]
source = "Docker"
service = "postgres"
image = "postgres:16-alpine"
variables = [
  { name = "POSTGRES_USER", value = "admin" },
  { name = "POSTGRES_PASSWORD", value = "10mega2013" },
  { name = "POSTGRES_DB", value = "dbn8n" },
  { name = "POSTGRES_NON_ROOT_USER", value = "admin" },
  { name = "POSTGRES_NON_ROOT_PASSWORD", value = "10mega2013" }
]

[plugins.qdrant]
source = "Docker"
service = "qdrant"
image = "qdrant/qdrant"
variables = []

# Volume do Qdrant configurado no Railway
[plugins.qdrant.volumes]
qdrant_storage = "/qdrant/storage"
